name: Record Awani HLS (Auto 5 Mins)

on:
  schedule:
    # Berjalan automatik setiap 5 minit
    - cron: '*/5 * * * *'
  workflow_dispatch: # Boleh juga tekan butang manual bila-bila masa

jobs:
  record-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Kebenaran untuk kemaskini fail dalam repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Empty and Recreate Awani Folder
        run: |
          rm -rf awani
          mkdir -p awani

      - name: Record 2 Minutes Stream
        run: |
          ffmpeg -y \
          -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 5 \
          -i "https://d2idp3hzkhjpih.cloudfront.net/out/v1/4b85d9c2bf97413eb0c9fd875599b837/index_1.m3u8" \
          -t 120 \
          -c copy \
          -f hls \
          -hls_time 10 \
          -hls_playlist_type vod \
          -hls_segment_filename "awani/segment%d.ts" \
          awani/index.m3u8

      - name: Commit and Push Updated Awani Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add awani/
          git commit -m "Auto-update Awani stream segmen [$(date '+%Y-%m-%d %H:%M:%S')]" || exit 0
          git push
          
